name: Release
on:
    push:
        branches:
            - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: pnpm/action-setup@v3

            - name: Setup Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Prepare Machine Emulator
              working-directory: machine-emulator
              run: |
                  make dep
                  make bundle-boost

            - name: Install Dependencies
              run: pnpm install

            - name: Create Release Pull Request
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
